remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
domain: chunkytofustudios.com
url: https://chunkytofustudios.com
title: Chunky Tofu Studios
description: Yet another game studios publishing fun apps.
logo: /assets/img/logo.png # not used
show_downloads: false
google_analytics: G-REYS4TKJBK
