remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Chunky Tofu Studios
description: Yet another game studios publishing fun apps.
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
